drop table ACCOUNT if exists;
drop sequence S_ACCOUNT if exists;

drop table CUSTOMER if exists;
drop sequence S_CUSTOMER if exists;

drop table CREDITCARD if exists;
drop sequence S_CREDITCARD if exists;

create sequence S_ACCOUNT start with 1;
create sequence S_CUSTOMER start with 1;
create sequence S_CREDITCARD start with 1;

create table CUSTOMER (
  ID integer GENERATED BY DEFAULT AS SEQUENCE S_CUSTOMER primary key,
  FIRSTNAME VARCHAR(100),
  LASTNAME VARCHAR(100),
  PHONENUMBER VARCHAR(100),
  ADDRESS VARCHAR(100)
);

create table ACCOUNT (
  ID integer GENERATED BY DEFAULT AS SEQUENCE S_ACCOUNT primary key,
  BALANCE integer,
  CUSTOMER_ID integer unique not null,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

create table CREDITCARD (
  ID integer GENERATED BY DEFAULT AS SEQUENCE S_CREDITCARD primary key,
  ISSUE_DATE timestamp,
  EXPIRATION_DATE timestamp,
  CUSTOMER_ID integer not null,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);